# -*- coding: utf-8 -*-
"""1_Python List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUT2rm6JbLHHwLCSswtYl61hoAHVjBpf
"""

print ("meena")

a= 10
b=10
c= a+b
print (c)

a=10
print (a)
id(a)

a=10
b=5
a=b
print (id(a))
print (id(b))
print(a)
print(b)

a=10
b=5
print(id(a))

print(id(b))

a=10
b=20
a=b
print(a)
print(b)
print(id(a))
print(id(b))

a="meena"
b=2.14
print (type(a))
print (type(b))

#List - print index value
a=[10,20,30,40,50,"meena"]
print (a[0])
print (a[0], a[1],a[2])

#slice in list
a=[10,20,30,40,50,"meena"]
print (a[0:6])

#append in list - value added in the last index

a=[10,20,30,40,50,"meena"]
a.append(60)
a.append(70)
print(a)

# extend in list - a list can be extended 

a=[10,20,30]
b=[40,50,60,70,80]
a.extend(b)
print (b)
print (a)

# insert a value in list - we can insert a value by using a.insert(index,insert value)


a=[1,2,3,4,5,6,7,8,9,10]
a.insert(3,"meena")
print (a)

# remove a value from list - a.remove(value)

a=[1,2,3,4,5,6,7,8,9,10]
a.remove(2)
print (a)

a=[1,2,3,4,5,6,7,8,9,10]
a.remove(3)
print (a)

# pop operation in list - a.pop() - it will pop the last value and shows that which item is deleted.

a=[1,2,3,4,5]
a.pop()
print (a)

# pop - we can alao pop the items based on index values.
a=[1,2,3,4,5]
a.pop(3)
print (a)

# clear - a.clear() - we can clear all the values within the list
a=[1,2,3,4,5]
a.clear()
print (a)

# Copy - we can copy the items in the list - x=a.copy()

a=[1,2,3,4,5]
x= a.copy()
print(x)

# we can count the values in the list
a=[1,2,3,4,5,6,7,8,8]
c=a.count(8)
print (c)

# we can find the index value in the list
a=[1,2,3,4,5,6]
a.index(3)